
server:
  port: 9191

spring:
  application:
    name: erwin-message
  profiles:
    active: dev

  mail:
    # 设置邮箱主机
    ##邮箱服务器地址
    ##QQ smtp.qq.com
    ##sina smtp.sina.cn
    ##aliyun smtp.aliyun.com
    ##163 smtp.163.com
    host: smtp.163.com
    # 设置用户名
    username:
    # 设置密码，邮箱开启SMTP的授权码而非QQ密码
    password:
    properties:
      mail:
        smtp:
          ssl:
            enable: true


#mybatis
mybatis-plus:
  # xml
  mapper-locations: classpath:mapper/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.fengwenyi.erwinmessage.entity
  # 扫描枚举类 # 支持统配符 * 或者 ; 分割
  type-enums-package: com.fengwenyi.erwinmessage.entity.enums
  global-config:
    db-config:
      #数据库大写下划线转换
      capital-mode: true
      #逻辑删除配置
      # logic-delete-field: delete_status # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑删除
      logic-not-delete-value: 0 # 正常
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler

jwt:
  secret: secret
  # 1000 * 60 * 60 * 8
  expiration: 28800000
  header: token

netty:
  socket:
    ip: 0.0.0.0
    port: 8090


